var demo_buttons = {
	"BLANK-conf0":{
		1:{"text":" ","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":" ","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":" ","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":" ","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":" ","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":" ","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":" ","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":" ","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":" ","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":" ","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		11:{"text":" ","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":" ","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":" ","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":" ","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":" ","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":" ","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":" ","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":" ","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":" ","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":" ","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
		21:{"text":" ","trigger":"21","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":" ","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":" ","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":" ","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":" ","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":" ","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":" ","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":" ","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"LABELED-conf0":{
		1:{"text":"1","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"2","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"3","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"4","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"5","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"6","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"7","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"8","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"9","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"10","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		11:{"text":"11","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"12","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"13","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"14","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"15","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"16","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"17","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"18","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"19","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"20","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
		21:{"text":"21","trigger":"21","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"MSFS_LEFT-conf0":{
		13:{"text":"RADIO","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"MSFS_LEFT-conf1":{
		1:{"text":"COMM1","trigger":"800","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"COMM2","trigger":"801","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"ATC","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"COMM3","trigger":"802","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"COMM4","trigger":"803","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"MAIN","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[6]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[7]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[8]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[9]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[10]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F15C-conf0":{
		4:{"text":"TGT PREV","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"TGT NEXT","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"RDR ON/OFF","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"RWS/TWS","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"PRF SEL","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"RWR/SPO","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"STORES","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"NAV","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"FLOOD","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"BORE","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"VS","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"BVR","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F15C-conf1":{
		13:{"text":"MAIN","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"NAV","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"DUMP","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"ORD","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"FUEL","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F15C-conf2":{
		1:{"text":"NAV","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"WPT PREV","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"WPT NEXT","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"STORES","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"MAIN","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"AP DIS","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"ATT HOLD","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"ALT HOLD","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_MIG29_L-conf0":{
		1:{"text":"EOS","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"TGT PREV","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"TGT NEXT","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"RDR ON/OFF","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"RWS/TWS","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"PRF SEL","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"RWR/SPO","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"STORES","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"NAV","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"LONG","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"HMD","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"BORE","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"VS","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"BVR","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_MIG29_L-conf1":{
		13:{"text":"MAIN","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"NAV","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"DUMP","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"ORD","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"FUEL","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_MIG29_L-conf2":{
		1:{"text":"NAV","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"WPT PREV","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"WPT NEXT","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"STORES","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"MAIN","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"AP PWR","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"AP GCAS","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"AP ATT","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"AP ALT","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"AP PATH","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_MIG29_R-conf0":{
		6:{"text":"HUD COL","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"BRT UP","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"BRT DN","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"ILLUM","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F14_L-conf0":{
		1:{"text":"GUN","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"AIM-9","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"SYS","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"ARM","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"HUD DCLT","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"ILS (HUD)","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"VDI NORM","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"ILS (VDI)","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"TACAN","trigger":"851","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"DEST","trigger":"852","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"AWL/PCD","trigger":"853","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"VEC","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		11:{"text":"MAN","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"T/O","trigger":"800","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"LAND","trigger":"801","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"CRUISE","trigger":"802","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"A/G","trigger":"803","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"A/A","trigger":"850","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F14_L-conf1":{
		3:{"text":"MAIN","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"HOOK","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"PARK","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"ANTISKID","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"O2","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"VSI PWR","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"HUD PWR","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F14_R-conf0":{
		16:{"text":"AUTO","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"RNG 25","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"RNG 50","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"RNG 100","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"RNG 200","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
		1:{"text":"LOCK FOE","trigger":"800","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"LOCK ANY","trigger":"801","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"UNLOCK","trigger":"852","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"VSL LO","trigger":"850","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"VSL HI","trigger":"851","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"P/PD","trigger":"853","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"RWS MODE","trigger":"802","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"TWS MODE","trigger":"803","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F5E_L-conf0":{
		6:{"text":"JETTISON","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"R WING","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		11:{"text":"R OBD","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"R IBD","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"CENT","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"L IBD","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"L OBD","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"L WING","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"ARM","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"JETT_UP","trigger":"0","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"JETT_DN","trigger":"0","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"ESTR_CCW","trigger":"0","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"ESTR_CW","trigger":"0","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"BOMB_CCW","trigger":"803","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"BOMB-CW","trigger":"804","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F5E_R-conf0":{
		6:{"text":"AA1 GUNS","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"AA2 GUNS","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"MSL","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"MAN","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"OFF","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"RNG 5","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"RNG 10","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"RNG 20","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"RNG 40","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_LEFT-conf0":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":16,"vy":1,"vw":1,"vh":2},
		35:{"text":"▲<br />IDM","trigger":"35","vx":19,"vy":4,"vw":1,"vh":2},
		36:{"text":"IDM<br />▼","trigger":"36","vx":19,"vy":6,"vw":1,"vh":2},
		37:{"text":"▲<br />WCA","trigger":"37","vx":21,"vy":1,"vw":1,"vh":2},
		38:{"text":"WCA<br />▼","trigger":"38","vx":21,"vy":3,"vw":1,"vh":2},
		54:{"text":"▲<br />RTS","trigger":"54","vx":21,"vy":7,"vw":1,"vh":2},
		55:{"text":"RTS<br />▼","trigger":"55","vx":21,"vy":9,"vw":1,"vh":2},
		56:{"text":"P","trigger":"56","vx":26,"vy":8,"vw":3,"vh":1},
		57:{"text":"ENT","trigger":"57","vx":29,"vy":8,"vw":3,"vh":1},
		58:{"text":"STOPWATCH","trigger":"58","vx":26,"vy":9,"vw":3,"vh":1},
		59:{"text":"SWAP","trigger":"59","vx":29,"vy":9,"vw":3,"vh":1},
		40:{"text":"FCR","trigger":"40","vx":1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":3,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":5,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":11,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":13,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":13,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T1]","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T2]","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T5]<br />►","trigger":"conf4","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[R1]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R2]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"▼[R5]","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L5]▼","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_LEFT-conf1":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":16,"vy":1,"vw":1,"vh":2},
		35:{"text":"▲<br />IDM","trigger":"35","vx":19,"vy":4,"vw":1,"vh":2},
		36:{"text":"IDM<br />▼","trigger":"36","vx":19,"vy":6,"vw":1,"vh":2},
		37:{"text":"▲<br />WCA","trigger":"37","vx":21,"vy":1,"vw":1,"vh":2},
		38:{"text":"WCA<br />▼","trigger":"38","vx":21,"vy":3,"vw":1,"vh":2},
		54:{"text":"▲<br />RTS","trigger":"54","vx":21,"vy":7,"vw":1,"vh":2},
		55:{"text":"RTS<br />▼","trigger":"55","vx":21,"vy":9,"vw":1,"vh":2},
		56:{"text":"P","trigger":"56","vx":26,"vy":8,"vw":3,"vh":1},
		57:{"text":"ENT","trigger":"57","vx":29,"vy":8,"vw":3,"vh":1},
		58:{"text":"STOPWATCH","trigger":"58","vx":26,"vy":9,"vw":3,"vh":1},
		59:{"text":"SWAP","trigger":"59","vx":29,"vy":9,"vw":3,"vh":1},
		40:{"text":"FCR","trigger":"40","vx":1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":3,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":5,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":11,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":13,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":13,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T1]","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T2]","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T5]<br />►","trigger":"conf5","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"▲[R2]","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R5]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[R6]","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L5]▼","trigger":"conf3","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_LEFT-conf2":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":16,"vy":1,"vw":1,"vh":2},
		35:{"text":"▲<br />IDM","trigger":"35","vx":19,"vy":4,"vw":1,"vh":2},
		36:{"text":"IDM<br />▼","trigger":"36","vx":19,"vy":6,"vw":1,"vh":2},
		37:{"text":"▲<br />WCA","trigger":"37","vx":21,"vy":1,"vw":1,"vh":2},
		38:{"text":"WCA<br />▼","trigger":"38","vx":21,"vy":3,"vw":1,"vh":2},
		54:{"text":"▲<br />RTS","trigger":"54","vx":21,"vy":7,"vw":1,"vh":2},
		55:{"text":"RTS<br />▼","trigger":"55","vx":21,"vy":9,"vw":1,"vh":2},
		56:{"text":"P","trigger":"56","vx":26,"vy":8,"vw":3,"vh":1},
		57:{"text":"ENT","trigger":"57","vx":29,"vy":8,"vw":3,"vh":1},
		58:{"text":"STOPWATCH","trigger":"58","vx":26,"vy":9,"vw":3,"vh":1},
		59:{"text":"SWAP","trigger":"59","vx":29,"vy":9,"vw":3,"vh":1},
		40:{"text":"FCR","trigger":"40","vx":1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":3,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":5,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":11,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":13,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":13,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T1]","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T2]","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T5]<br />►","trigger":"conf6","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[R1]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R2]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"▼[R5]","trigger":"conf3","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L6]","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L2]▲","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_LEFT-conf3":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":16,"vy":1,"vw":1,"vh":2},
		35:{"text":"▲<br />IDM","trigger":"35","vx":19,"vy":4,"vw":1,"vh":2},
		36:{"text":"IDM<br />▼","trigger":"36","vx":19,"vy":6,"vw":1,"vh":2},
		37:{"text":"▲<br />WCA","trigger":"37","vx":21,"vy":1,"vw":1,"vh":2},
		38:{"text":"WCA<br />▼","trigger":"38","vx":21,"vy":3,"vw":1,"vh":2},
		54:{"text":"▲<br />RTS","trigger":"54","vx":21,"vy":7,"vw":1,"vh":2},
		55:{"text":"RTS<br />▼","trigger":"55","vx":21,"vy":9,"vw":1,"vh":2},
		56:{"text":"P","trigger":"56","vx":26,"vy":8,"vw":3,"vh":1},
		57:{"text":"ENT","trigger":"57","vx":29,"vy":8,"vw":3,"vh":1},
		58:{"text":"STOPWATCH","trigger":"58","vx":26,"vy":9,"vw":3,"vh":1},
		59:{"text":"SWAP","trigger":"59","vx":29,"vy":9,"vw":3,"vh":1},
		40:{"text":"FCR","trigger":"40","vx":1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":3,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":5,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":11,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":13,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":13,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T1]","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T2]","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T5]<br />►","trigger":"conf7","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"▲[R2]","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R5]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[R6]","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L6]","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L2]▲","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_LEFT-conf4":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":16,"vy":1,"vw":1,"vh":2},
		35:{"text":"▲<br />IDM","trigger":"35","vx":19,"vy":4,"vw":1,"vh":2},
		36:{"text":"IDM<br />▼","trigger":"36","vx":19,"vy":6,"vw":1,"vh":2},
		37:{"text":"▲<br />WCA","trigger":"37","vx":21,"vy":1,"vw":1,"vh":2},
		38:{"text":"WCA<br />▼","trigger":"38","vx":21,"vy":3,"vw":1,"vh":2},
		54:{"text":"▲<br />RTS","trigger":"54","vx":21,"vy":7,"vw":1,"vh":2},
		55:{"text":"RTS<br />▼","trigger":"55","vx":21,"vy":9,"vw":1,"vh":2},
		56:{"text":"P","trigger":"56","vx":26,"vy":8,"vw":3,"vh":1},
		57:{"text":"ENT","trigger":"57","vx":29,"vy":8,"vw":3,"vh":1},
		58:{"text":"STOPWATCH","trigger":"58","vx":26,"vy":9,"vw":3,"vh":1},
		59:{"text":"SWAP","trigger":"59","vx":29,"vy":9,"vw":3,"vh":1},
		40:{"text":"FCR","trigger":"40","vx":1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":3,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":5,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":11,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":13,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":13,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T2]<br />◄","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T5]","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T6]","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[R1]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R2]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"▼[R5]","trigger":"conf5","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L5]▼","trigger":"conf6","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_LEFT-conf5":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":16,"vy":1,"vw":1,"vh":2},
		35:{"text":"▲<br />IDM","trigger":"35","vx":19,"vy":4,"vw":1,"vh":2},
		36:{"text":"IDM<br />▼","trigger":"36","vx":19,"vy":6,"vw":1,"vh":2},
		37:{"text":"▲<br />WCA","trigger":"37","vx":21,"vy":1,"vw":1,"vh":2},
		38:{"text":"WCA<br />▼","trigger":"38","vx":21,"vy":3,"vw":1,"vh":2},
		54:{"text":"▲<br />RTS","trigger":"54","vx":21,"vy":7,"vw":1,"vh":2},
		55:{"text":"RTS<br />▼","trigger":"55","vx":21,"vy":9,"vw":1,"vh":2},
		56:{"text":"P","trigger":"56","vx":26,"vy":8,"vw":3,"vh":1},
		57:{"text":"ENT","trigger":"57","vx":29,"vy":8,"vw":3,"vh":1},
		58:{"text":"STOPWATCH","trigger":"58","vx":26,"vy":9,"vw":3,"vh":1},
		59:{"text":"SWAP","trigger":"59","vx":29,"vy":9,"vw":3,"vh":1},
		40:{"text":"FCR","trigger":"40","vx":1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":3,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":5,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":11,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":13,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":13,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T2]<br />◄","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T5]","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T6]","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"▲[R2]","trigger":"conf4","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R5]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[R6]","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L5]▼","trigger":"conf7","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_LEFT-conf6":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":16,"vy":1,"vw":1,"vh":2},
		35:{"text":"▲<br />IDM","trigger":"35","vx":19,"vy":4,"vw":1,"vh":2},
		36:{"text":"IDM<br />▼","trigger":"36","vx":19,"vy":6,"vw":1,"vh":2},
		37:{"text":"▲<br />WCA","trigger":"37","vx":21,"vy":1,"vw":1,"vh":2},
		38:{"text":"WCA<br />▼","trigger":"38","vx":21,"vy":3,"vw":1,"vh":2},
		54:{"text":"▲<br />RTS","trigger":"54","vx":21,"vy":7,"vw":1,"vh":2},
		55:{"text":"RTS<br />▼","trigger":"55","vx":21,"vy":9,"vw":1,"vh":2},
		56:{"text":"P","trigger":"56","vx":26,"vy":8,"vw":3,"vh":1},
		57:{"text":"ENT","trigger":"57","vx":29,"vy":8,"vw":3,"vh":1},
		58:{"text":"STOPWATCH","trigger":"58","vx":26,"vy":9,"vw":3,"vh":1},
		59:{"text":"SWAP","trigger":"59","vx":29,"vy":9,"vw":3,"vh":1},
		40:{"text":"FCR","trigger":"40","vx":1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":3,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":5,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":11,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":13,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":13,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T2]<br />◄","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T5]","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T6]","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[R1]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R2]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"▼[R5]","trigger":"conf7","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L6]","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L2]▲","trigger":"conf4","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_LEFT-conf7":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":16,"vy":1,"vw":1,"vh":2},
		35:{"text":"▲<br />IDM","trigger":"35","vx":19,"vy":4,"vw":1,"vh":2},
		36:{"text":"IDM<br />▼","trigger":"36","vx":19,"vy":6,"vw":1,"vh":2},
		37:{"text":"▲<br />WCA","trigger":"37","vx":21,"vy":1,"vw":1,"vh":2},
		38:{"text":"WCA<br />▼","trigger":"38","vx":21,"vy":3,"vw":1,"vh":2},
		54:{"text":"▲<br />RTS","trigger":"54","vx":21,"vy":7,"vw":1,"vh":2},
		55:{"text":"RTS<br />▼","trigger":"55","vx":21,"vy":9,"vw":1,"vh":2},
		56:{"text":"P","trigger":"56","vx":26,"vy":8,"vw":3,"vh":1},
		57:{"text":"ENT","trigger":"57","vx":29,"vy":8,"vw":3,"vh":1},
		58:{"text":"STOPWATCH","trigger":"58","vx":26,"vy":9,"vw":3,"vh":1},
		59:{"text":"SWAP","trigger":"59","vx":29,"vy":9,"vw":3,"vh":1},
		40:{"text":"FCR","trigger":"40","vx":1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":3,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":5,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":11,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":13,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":13,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T2]<br />◄","trigger":"conf3","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T5]","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T6]","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"▲[R2]","trigger":"conf6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R5]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[R6]","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L6]","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L2]▲","trigger":"conf5","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_RIGHT-conf0":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":-3,"vy":1,"vw":1,"vh":2},
		40:{"text":"FCR","trigger":"40","vx":-1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":-1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":1,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":3,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":9,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":11,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":11,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T1]","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T2]","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T5]<br />►","trigger":"conf4","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[R1]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R2]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"▼[R5]","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L5]▼","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_RIGHT-conf1":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":-3,"vy":1,"vw":1,"vh":2},
		40:{"text":"FCR","trigger":"40","vx":-1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":-1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":1,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":3,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":9,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":11,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":11,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T1]","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T2]","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T5]<br />►","trigger":"conf5","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"▲[R2]","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R5]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[R6]","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L5]▼","trigger":"conf3","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_RIGHT-conf2":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":-3,"vy":1,"vw":1,"vh":2},
		40:{"text":"FCR","trigger":"40","vx":-1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":-1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":1,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":3,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":9,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":11,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":11,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T1]","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T2]","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T5]<br />►","trigger":"conf6","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[R1]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R2]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"▼[R5]","trigger":"conf3","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L6]","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L2]▲","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_RIGHT-conf3":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":-3,"vy":1,"vw":1,"vh":2},
		40:{"text":"FCR","trigger":"40","vx":-1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":-1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":1,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":3,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":9,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":11,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":11,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T1]","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T2]","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T5]<br />►","trigger":"conf7","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"▲[R2]","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R5]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[R6]","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L6]","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L2]▲","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_RIGHT-conf4":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":-3,"vy":1,"vw":1,"vh":2},
		40:{"text":"FCR","trigger":"40","vx":-1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":-1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":1,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":3,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":9,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":11,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":11,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T2]<br />◄","trigger":"conf0","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T5]","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T6]","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[R1]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R2]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"▼[R5]","trigger":"conf5","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L5]▼","trigger":"conf6","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_RIGHT-conf5":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":-3,"vy":1,"vw":1,"vh":2},
		40:{"text":"FCR","trigger":"40","vx":-1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":-1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":1,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":3,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":9,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":11,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":11,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T2]<br />◄","trigger":"conf1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T5]","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T6]","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"▲[R2]","trigger":"conf4","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R5]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[R6]","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L5]▼","trigger":"conf7","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L2]","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L1]","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_RIGHT-conf6":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":-3,"vy":1,"vw":1,"vh":2},
		40:{"text":"FCR","trigger":"40","vx":-1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":-1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":1,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":3,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":9,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":11,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":11,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T2]<br />◄","trigger":"conf2","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T5]","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T6]","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"[R1]","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R2]","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"▼[R5]","trigger":"conf7","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L6]","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L2]▲","trigger":"conf4","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"AH64_RIGHT-conf7":{
		11:{"text":"[B5]","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"[B4]","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"[B3]","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"[B2]","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"[B1]","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"*","trigger":"33","vx":-3,"vy":1,"vw":1,"vh":2},
		40:{"text":"FCR","trigger":"40","vx":-1,"vy":17,"vw":2,"vh":1},
		41:{"text":"WPN","trigger":"41","vx":-1,"vy":18,"vw":2,"vh":1},
		42:{"text":"TSD","trigger":"42","vx":1,"vy":19,"vw":2,"vh":1},
		43:{"text":"M","trigger":"43","vx":3,"vy":19,"vw":1,"vh":1},
		44:{"text":"A/C","trigger":"44","vx":9,"vy":19,"vw":2,"vh":1},
		45:{"text":"COM","trigger":"45","vx":11,"vy":18,"vw":2,"vh":1},
		46:{"text":"VID","trigger":"46","vx":11,"vy":17,"vw":2,"vh":1},
		1:{"text":"[T2]<br />◄","trigger":"conf3","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"[T3]","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"[T4]","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"[T5]","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"[T6]","trigger":"29","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"▲[R2]","trigger":"conf6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"[R3]","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"[R4]","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"[R5]","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"[R6]","trigger":"31","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"[L6]","trigger":"30","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"[L5]","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"[L4]","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"[L3]","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"[L2]▲","trigger":"conf5","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"DCS_F1CE_Right-conf0":{
		20:{"text":"EXT.G","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"M.G.F S","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"CAN.A","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"BOMB VOIL","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"EXT.D","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"M.D.","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"CAN.S ROQ","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"BOMB FUS","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
	},
	"BLANK64-conf0":{
		1:{"text":" ","trigger":"33","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":" ","trigger":"34","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":" ","trigger":"35","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":" ","trigger":"36","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":" ","trigger":"37","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":" ","trigger":"38","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":" ","trigger":"39","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":" ","trigger":"40","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":" ","trigger":"41","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":" ","trigger":"42","vx":false,"vy":false,"vw":false,"vh":false},
		11:{"text":" ","trigger":"43","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":" ","trigger":"44","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":" ","trigger":"45","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":" ","trigger":"46","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":" ","trigger":"47","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":" ","trigger":"48","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":" ","trigger":"49","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":" ","trigger":"50","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":" ","trigger":"51","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":" ","trigger":"52","vx":false,"vy":false,"vw":false,"vh":false},
		21:{"text":" ","trigger":"53","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":" ","trigger":"54","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":" ","trigger":"55","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":" ","trigger":"56","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":" ","trigger":"57","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":" ","trigger":"58","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":" ","trigger":"59","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":" ","trigger":"60","vx":false,"vy":false,"vw":false,"vh":false},
		40:{"text":"Test1","trigger":"61","vx":22,"vy":20,"vw":4,"vh":1},
		41:{"text":"Test2","trigger":"62","vx":22,"vy":21,"vw":4,"vh":1},
		42:{"text":"Test3","trigger":"63","vx":26,"vy":20,"vw":4,"vh":1},
		43:{"text":"Test4","trigger":"64","vx":26,"vy":21,"vw":4,"vh":1},
	},
	"DCS_F15E_LEFT-conf0":{
		1:{"text":"20","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"19","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"18","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"17","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"16","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"15","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"14","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"13","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"12","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"11","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		11:{"text":"10","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"9","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"8","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"7","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"6","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"5","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"4","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"3","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"2","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"1","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
		21:{"text":"21","trigger":"21","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"1","trigger":"33","vx":21,"vy":18,"vw":2,"vh":2},
		34:{"text":"2","trigger":"34","vx":21,"vy":20,"vw":2,"vh":2},
		35:{"text":"3","trigger":"35","vx":21,"vy":22,"vw":2,"vh":2},
		36:{"text":"4","trigger":"36","vx":21,"vy":24,"vw":2,"vh":2},
		37:{"text":"5","trigger":"37","vx":21,"vy":26,"vw":2,"vh":2},
		38:{"text":"6","trigger":"38","vx":23,"vy":28,"vw":2,"vh":2},
		39:{"text":"7","trigger":"39","vx":25,"vy":28,"vw":2,"vh":2},
		40:{"text":"8","trigger":"40","vx":27,"vy":28,"vw":2,"vh":2},
		41:{"text":"9","trigger":"41","vx":29,"vy":28,"vw":2,"vh":2},
		42:{"text":"10","trigger":"42","vx":31,"vy":28,"vw":2,"vh":2},
		43:{"text":"11","trigger":"43","vx":33,"vy":26,"vw":2,"vh":2},
		44:{"text":"12","trigger":"44","vx":33,"vy":24,"vw":2,"vh":2},
		45:{"text":"13","trigger":"45","vx":33,"vy":22,"vw":2,"vh":2},
		46:{"text":"14","trigger":"46","vx":33,"vy":20,"vw":2,"vh":2},
		47:{"text":"15","trigger":"47","vx":33,"vy":18,"vw":2,"vh":2},
		48:{"text":"R","trigger":"48","vx":31,"vy":16,"vw":2,"vh":2},
		49:{"text":"RC","trigger":"49","vx":29,"vy":16,"vw":2,"vh":2},
		50:{"text":"C","trigger":"50","vx":27,"vy":16,"vw":2,"vh":2},
		51:{"text":"LC","trigger":"51","vx":25,"vy":16,"vw":2,"vh":2},
		52:{"text":"L","trigger":"52","vx":23,"vy":16,"vw":2,"vh":2},
		53:{"text":"TF RDR<br />ON","trigger":"53","vx":2,"vy":17,"vw":2,"vh":2},
		54:{"text":"TF RDR<br />OFF","trigger":"54","vx":2,"vy":19,"vw":2,"vh":2},
		55:{"text":"RALT<br />OVRD","trigger":"55","vx":5,"vy":17,"vw":2,"vh":2},
		56:{"text":"RALT<br />OFF","trigger":"56","vx":5,"vy":19,"vw":2,"vh":2},
		57:{"text":"RDR ON/STBY","trigger":"57","vx":11,"vy":16,"vw":3,"vh":2},
		58:{"text":"RDR OFF/STBY","trigger":"58","vx":11,"vy":18,"vw":3,"vh":2},
	},
	"DCS_F15E_RIGHT-conf0":{
		1:{"text":"20","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"19","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		3:{"text":"18","trigger":"3","vx":false,"vy":false,"vw":false,"vh":false},
		4:{"text":"17","trigger":"4","vx":false,"vy":false,"vw":false,"vh":false},
		5:{"text":"16","trigger":"5","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"15","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"14","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"13","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		9:{"text":"12","trigger":"9","vx":false,"vy":false,"vw":false,"vh":false},
		10:{"text":"11","trigger":"10","vx":false,"vy":false,"vw":false,"vh":false},
		11:{"text":"10","trigger":"11","vx":false,"vy":false,"vw":false,"vh":false},
		12:{"text":"9","trigger":"12","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"8","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"7","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"6","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		16:{"text":"5","trigger":"16","vx":false,"vy":false,"vw":false,"vh":false},
		17:{"text":"4","trigger":"17","vx":false,"vy":false,"vw":false,"vh":false},
		18:{"text":"3","trigger":"18","vx":false,"vy":false,"vw":false,"vh":false},
		19:{"text":"2","trigger":"19","vx":false,"vy":false,"vw":false,"vh":false},
		20:{"text":"1","trigger":"20","vx":false,"vy":false,"vw":false,"vh":false},
		21:{"text":"21","trigger":"21","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":"22","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":"23","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":"24","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":"25","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":"26","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":"27","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":"28","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
		33:{"text":"A/A","trigger":"33","vx":-21,"vy":13,"vw":3,"vh":2},
		34:{"text":"A/G","trigger":"34","vx":-18,"vy":13,"vw":3,"vh":2},
		35:{"text":"NAV","trigger":"35","vx":-15,"vy":13,"vw":3,"vh":2},
		36:{"text":"INST","trigger":"36","vx":-12,"vy":13,"vw":3,"vh":2},
		40:{"text":" ","trigger":"40","vx":-27,"vy":1,"vw":2,"vh":2},
		41:{"text":" ","trigger":"41","vx":-27,"vy":3,"vw":2,"vh":2},
		42:{"text":" ","trigger":"42","vx":-27,"vy":5,"vw":2,"vh":2},
		43:{"text":" ","trigger":"43","vx":-27,"vy":7,"vw":2,"vh":2},
		44:{"text":" ","trigger":"44","vx":-27,"vy":9,"vw":2,"vh":2},
		45:{"text":" ","trigger":"45","vx":-4,"vy":1,"vw":2,"vh":2},
		46:{"text":" ","trigger":"46","vx":-4,"vy":3,"vw":2,"vh":2},
		47:{"text":" ","trigger":"47","vx":-4,"vy":5,"vw":2,"vh":2},
		48:{"text":" ","trigger":"48","vx":-4,"vy":7,"vw":2,"vh":2},
		49:{"text":" ","trigger":"49","vx":-4,"vy":9,"vw":2,"vh":2},
	},
	"F86F_L-conf0":{
		1:{"text":"GUNS","trigger":"1","vx":false,"vy":false,"vw":false,"vh":false},
		2:{"text":"MSL","trigger":"2","vx":false,"vy":false,"vw":false,"vh":false},
		15:{"text":"LWR","trigger":"15","vx":false,"vy":false,"vw":false,"vh":false},
		14:{"text":"MID","trigger":"14","vx":false,"vy":false,"vw":false,"vh":false},
		13:{"text":"ALL","trigger":"13","vx":false,"vy":false,"vw":false,"vh":false},
		6:{"text":"LABS<br />ON","trigger":"6","vx":false,"vy":false,"vw":false,"vh":false},
		7:{"text":"LABS<br />A-4","trigger":"7","vx":false,"vy":false,"vw":false,"vh":false},
		8:{"text":"CAGE<br />UNCAGE","trigger":"8","vx":false,"vy":false,"vw":false,"vh":false},
		21:{"text":" ","trigger":"21","vx":false,"vy":false,"vw":false,"vh":false},
		22:{"text":" ","trigger":"22","vx":false,"vy":false,"vw":false,"vh":false},
		23:{"text":" ","trigger":"23","vx":false,"vy":false,"vw":false,"vh":false},
		24:{"text":" ","trigger":"24","vx":false,"vy":false,"vw":false,"vh":false},
		25:{"text":" ","trigger":"25","vx":false,"vy":false,"vw":false,"vh":false},
		26:{"text":" ","trigger":"26","vx":false,"vy":false,"vw":false,"vh":false},
		27:{"text":" ","trigger":"27","vx":false,"vy":false,"vw":false,"vh":false},
		28:{"text":" ","trigger":"28","vx":false,"vy":false,"vw":false,"vh":false},
	},
};